# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "chef/centos-6.6"

  config.vm.network "forwarded_port", guest: 8080, host: 2345
  config.vm.network "forwarded_port", guest: 8443, host: 2346
  config.vm.network "forwarded_port", guest: 65000, host: 65000
  config.vm.network "private_network", ip: "192.168.44.10"

  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "guestproperty", "set", :id, "--timesync-threshold", 10000 ]
  end

  config.vm.synced_folder "../", "/home/vagrant/testSpringJenkins"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/acit_dev.yml"
    ansible.host_key_checking = false
  end
end
