---
- name: Create a database for Sonar
  postgresql_db:
    name={{ sonar_pgsql_database }}
    state=present
    port={{ sonar_pgsql_port }}

- name: Create a sonar user
  postgresql_user:
    db={{ sonar_pgsql_database }}
    name={{ sonar_pgsql_user }}
    password={{ sonar_pgsql_password }}
    port={{ sonar_pgsql_port }}

- name: Download Sonar
  get_url:
    url: "{{ sonar_download_url }}"
    dest: "{{ workspace }}/{{ sonar_version_directory }}.zip"

- name: Unzip Sonar
  shell: >
    chdir={{ workspace }}
    unzip -o {{ workspace }}/{{ sonar_version_directory }}.zip
    creates=/usr/local/sonar/COPYING
  sudo: yes

- name: Move Sonar into place
  shell: >
    mv {{ workspace }}/{{ sonar_version_directory }} /usr/local/sonar
    creates=/usr/local/sonar/COPYING

- name: Copy sonar properties file
  template:
    src: sonar.properties.j2
    dest: /usr/local/sonar/conf/sonar.properties
  notify: restart sonar

- name: Add sonar symlinks for service management
  file:
    src: /usr/local/sonar/bin/linux-x86-64/sonar.sh
    dest: "{{ item }}"
    state: link
  with_items:
    - /usr/bin/sonar
    - /etc/init.d/sonar

- name: Ensure Sonar is running and set to start on boot.
  service: name=sonar state=started enabled=yes
