---


- name: Install base packages
  yum:
    pkg={{ item }}
    state=latest
  with_items:
    - libselinux-python
    - unzip
    - wget

- name: Create ansible-cache directory
  file:
    path={{ ansible_cache_folder }}
    state=directory